### ISSUE TITLE
Design and Fabricate a model Rocket Airframe.

### ISSUE THREAD

**Issue by dmashy** [nakujaproject/nakujaproject.github.io#11]
Design using SolidWorks/Inventor
Fabricate using 3D printing

**Comment by rodneyosodo** [comment]
Working on it

**Comment by rodneyosodo** [comment]
Done

**Comment by dmashy** [comment]
Thank you brother

We can get the 3D printing starting Wednesday or they managed to repair
yesterday

**Comment by rodneyosodo** [comment]
They didn't manage to repair it on Tuesday

**Comment by dmashy** [comment]
Ok, thanks for the update.
